#'@title Find the lower or upper bound for one parameter
#'
#'@description Find the lower or upper bound for one parameter.
#'
#'@details
#'
#' Currently supports \code{lavaan} output only.
#'
#'@return
#' The requested bound.
#' Can return the optimization history as an attribute.
#'
#' @param i The position of the target parameters as in the parameter table of lavaan.
#' @param npar The number of free parameters, including those constrained to be equal.
#' @param sem_out The fit object.
#' @param f_constr The constraint function generated by \code{set_constraint}.
#' @param which Whether the lower bound or the upper bound is to be found. Must be "lbound" or "ubound".
#' @param history If \code{TRUE}, return the full optimization output as an attribute. Default is \code{FALSE}.
#' @param perturbation_factor A number multiplied to the parameter estimates in the fit object.
#'                            Using the parameter estimates as starting values may lead to errors
#'                            in the first few iterations. Default is .90.
#' @param lb_var The lower bound for free parameters that are variances. Defautl is -Inf. This is not an admissible
#'                value but seems to be necessary when we need to find the LBCI for user-defined parameter.
#' @param wald_ci_start If TRUE and there are no equality constraints in the model, Wald confidence limit will
#'                       be used as the starting value for the target parameter if it is not a userd-defined paramter.
#' @param standardized If TRUE, the LBCI is for the standardized estimate. 
#' @param opts Options to be passed to \code{nloptr}
#' @param ... Optional arguments. Not used.
#' 
#'@examples
#' library(lavaan)
#' data(cfa_two_factors)
#' mod <-
#' "
#' f1 =~ x1 + x2 + a*x3
#' f2 =~ x4 + a*x5 + equal('f1=~x2')*x6
#' f1 ~~ 0*f2
#' asq := a^2
#' "
#' fit <- sem(mod, cfa_two_factors)
#'@export

ci_bound_i <- function(i = NULL, 
                       npar = NULL, 
                       sem_out = NULL,
                       f_constr = NULL, 
                       which = NULL,
                       history = FALSE,
                       perturbation_factor = .9,
                       lb_var = -Inf,
                       wald_ci_start = TRUE,
                       standardized = FALSE,
                       opts = list(
                          "algorithm" = "NLOPT_LD_SLSQP",
                          "xtol_rel" = 1.0e-10,
                          "maxeval" = 1000,
                          "print_level" = 0),
                       ...) {
    k <- switch(which,
                lbound = 1,
                ubound = -1)
    # Check if the parameter is a user-defined parameter
    p_table <- lavaan::parameterTable(sem_out) 
    i_op <- p_table[i, "op"]
    if (standardized && (i_op %in% c("=~", "~", "~~", ":="))) {
        p_std <- lavaan::standardizedSolution(sem_out,
                                              type = "std.all",
                                              se = FALSE,
                                              zstat = FALSE,
                                              pvalue = FALSE,
                                              ci = FALSE,
                                              remove.eq = FALSE,
                                              remove.ineq = FALSE,
                                              remove.def = FALSE,
                                              output = "data.frame")
        p_std$id <- seq_len(nrow(p_std))
        i_lor <- get_lhs_op_rhs(i, sem_out)
        i_std <- merge(p_std, i_lor, by = c("lhs", "op", "rhs"))$id
        start0 <- lavaan::parameterTable(sem_out)
        # The function to be minimized.
        lbci_b_f <- function(param, sem_out, debug, lav_warn) {
            start1 <- start0
            start1[start1$free > 0, "est"] <- param
            sem_out2 <- sem_out
            sem_out2@ParTable <- as.list(start1)
            sem_model <- sem_out2@Model
            sem_model <- update_model(sem_model, 
                                      start1[start1$free > 0, "est"] )
            sem_out2@Model <- sem_model
            std0 <- lavaan::standardizedSolution(sem_out2,
                                            type = "std.all",
                                            se = FALSE,
                                            zstat = FALSE,
                                            pvalue = FALSE,
                                            ci = FALSE,
                                            remove.eq = FALSE,
                                            remove.ineq = FALSE,
                                            remove.def = FALSE,
                                            output = "data.frame")
            k * std0[i_std, "est.std"]
          }
        # The gradient of the function to be minimized
        lbci_b_grad <- function(param, sem_out, debug, lav_warn) {
            numDeriv::grad(lbci_b_f, param, sem_out = sem_out, 
                                    debug = debug, lav_warn = lav_warn)
          }
      }
    if (i_op == ":=") {
        if (standardized) {
            # # To be deleted
            # # Copied from the block for standardized free parameters.
            # # If works, should merge the two blocks together
            # p_std <- lavaan::standardizedSolution(sem_out,
            #                                       type = "std.all",
            #                                       se = FALSE,
            #                                       zstat = FALSE,
            #                                       pvalue = FALSE,
            #                                       ci = FALSE,
            #                                       remove.eq = FALSE,
            #                                       remove.ineq = FALSE,
            #                                       remove.def = FALSE,
            #                                       output = "data.frame")
            # p_std$id <- seq_len(nrow(p_std))
            # i_lor <- get_lhs_op_rhs(i, sem_out)
            # i_std <- merge(p_std, i_lor, by = c("lhs", "op", "rhs"))$id
            # start0 <- lavaan::parameterTable(sem_out)
            # # The function to be minimized.
            # lbci_b_f <- function(param, sem_out, debug, lav_warn) {
            #     start1 <- start0
            #     start1[start1$free > 0, "est"] <- param
            #     sem_out2 <- sem_out
            #     sem_out2@ParTable <- as.list(start1)
            #     sem_model <- sem_out2@Model
            #     sem_model <- update_model(sem_model, 
            #                               start1[start1$free > 0, "est"] )
            #     sem_out2@Model <- sem_model
            #     std0 <- lavaan::standardizedSolution(sem_out2,
            #                                     type = "std.all",
            #                                     se = FALSE,
            #                                     zstat = FALSE,
            #                                     pvalue = FALSE,
            #                                     ci = FALSE,
            #                                     remove.eq = FALSE,
            #                                     remove.ineq = FALSE,
            #                                     remove.def = FALSE,
            #                                     output = "data.frame")
            #     k * std0[i_std, "est.std"]
            #   }
            # # The gradient of the function to be minimized
            # lbci_b_grad <- function(param, sem_out, debug, lav_warn) {
            #     numDeriv::grad(lbci_b_f, param, sem_out = sem_out, 
            #                             debug = debug, lav_warn = lav_warn)
            #   }
          } else {
            # Get the name of the defined parameter
            i_name <- p_table[i, "label"]
            # The function to be minimized.
            lbci_b_f <- function(param, sem_out, debug, lav_warn) {
                k * sem_out@Model@def.function(param)[i_name]
              }
            # The gradient of the function to be minimized
            lbci_b_grad <- function(param, sem_out, debug, lav_warn) {
                numDeriv::grad(lbci_b_f, param, sem_out = sem_out, 
                                        debug = debug, lav_warn = lav_warn)
              }            
          }
      } else {
        if (standardized) {
            # # To be deleted:
            # p_std <- lavaan::standardizedSolution(sem_out,
            #                                       type = "std.all",
            #                                       se = FALSE,
            #                                       zstat = FALSE,
            #                                       pvalue = FALSE,
            #                                       ci = FALSE,
            #                                       remove.eq = FALSE,
            #                                       remove.ineq = FALSE,
            #                                       remove.def = FALSE,
            #                                       output = "data.frame")
            # p_std$id <- seq_len(nrow(p_std))
            # i_lor <- get_lhs_op_rhs(i, sem_out)
            # i_std <- merge(p_std, i_lor, by = c("lhs", "op", "rhs"))$id
            # start0 <- lavaan::parameterTable(sem_out)
            # # The function to be minimized.
            # lbci_b_f <- function(param, sem_out, debug, lav_warn) {
            #     start1 <- start0
            #     start1[start1$free > 0, "est"] <- param
            #     sem_out2 <- sem_out
            #     sem_out2@ParTable <- as.list(start1)
            #     sem_model <- sem_out2@Model
            #     sem_model <- update_model(sem_model, 
            #                               start1[start1$free > 0, "est"] )
            #     sem_out2@Model <- sem_model
            #     std0 <- lavaan::standardizedSolution(sem_out2,
            #                                     type = "std.all",
            #                                     se = FALSE,
            #                                     zstat = FALSE,
            #                                     pvalue = FALSE,
            #                                     ci = FALSE,
            #                                     remove.eq = FALSE,
            #                                     remove.ineq = FALSE,
            #                                     remove.def = FALSE,
            #                                     output = "data.frame")
            #     k * std0[i_std, "est.std"]
            #   }
            # # The gradient of the function to be minimized
            # lbci_b_grad <- function(param, sem_out, debug, lav_warn) {
            #     numDeriv::grad(lbci_b_f, param, sem_out = sem_out, 
            #                             debug = debug, lav_warn = lav_warn)
            #   }
          } else {
            # The function to be minimized.
            lbci_b_f <- function(param, sem_out, debug, lav_warn) {
                k * param[i]
              }
            # The gradient of the function to be minimized
            grad_c <- rep(0, npar)
            grad_c[i] <- k
            lbci_b_grad <- function(param, sem_out, debug, lav_warn) {
                    grad_c
              }
          }
      }
    if (wald_ci_start & !sem_out@Model@eq.constraints) {
        if (i_op == ":=") {
              xstart <- set_start(i, sem_out, which)
              xstart <- xstart[xstart$free > 0, "est"]
            } else {
              if (standardized) {
                  xstart <- set_start(i, sem_out, which, standardized)
                  xstart <- xstart[xstart$free > 0, "est"]
                } else {
                  xstart <- set_start(i, sem_out, which)
                  xstart <- xstart[xstart$free > 0, "est"]
                }
            } 
      } else {
        xstart <- perturbation_factor * lavaan::coef(sem_out)
      }
    fit_lb <- rep(-Inf, npar)
    fit_lb[find_variance_in_free(sem_out)] <- lb_var
    out <- nloptr::nloptr(
                        x0 = xstart, 
                        eval_f = lbci_b_f, 
                        lb = fit_lb, # To-Do: Check
                        ub = rep( Inf, npar), # To-Do: Check
                        eval_grad_f = lbci_b_grad,
                        eval_g_eq = f_constr,
                        opts = opts,
                        sem_out = sem_out,
                        lav_warn = FALSE,
                        debug = FALSE)
    bound <- k * out$objective

    # Check whether admissible
    start0 <- lavaan::parameterTable(sem_out)
    i_free <- find_free(sem_out)
    start0[i_free, "est"] <- out$solution
    fit_final <- lavaan::update(sem_out, start = start0, do.fit = FALSE,
                                check.start = TRUE,
                                check.post = TRUE,
                                check.vcov = TRUE)
    fit_post_check <- lavaan::lavInspect(fit_final, "post.check")
    if (!fit_post_check) {
        bound <- NA
        warning("Optimization converged but the final solution is not admissible.")
      }
    if (history) {
        attr(bound, "history") <- out
      }
    bound
  }
